// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTVXG0XKGcN86g_DtZTIIF6HyD1j4RfjE',
    appId: '1:559560831009:web:b4b6dfe75492a51adb7360',
    messagingSenderId: '559560831009',
    projectId: 'simulasi-kredit-b6c6d',
    authDomain: 'simulasi-kredit-b6c6d.firebaseapp.com',
    storageBucket: 'simulasi-kredit-b6c6d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMzmA3Kgv0KcEsPsWKk0TwYaNEjLpclIw',
    appId: '1:559560831009:android:fafb46600de80341db7360',
    messagingSenderId: '559560831009',
    projectId: 'simulasi-kredit-b6c6d',
    storageBucket: 'simulasi-kredit-b6c6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmR0TSOVM9pmLS0_MvNAtF8cQ6L4yHcF4',
    appId: '1:559560831009:ios:095de483fd911e12db7360',
    messagingSenderId: '559560831009',
    projectId: 'simulasi-kredit-b6c6d',
    storageBucket: 'simulasi-kredit-b6c6d.appspot.com',
    iosClientId: '559560831009-pr8sj3hfk41c0auv21po0sn77rd5t88a.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiSimulasiKredit',
  );
}
